name: Cache Name and NPM Dependencies
description: This action allows to cache Node and NPM

inputs:
  node-version:
    description: NodeJS version to use
    default: 20.x
    required: true
  working-dir:
    description: The working directory of the application
    default: .
    required: false
  target-env:
    description: '"dev" or "prod"'
    default: dev
    required: false

runs:
  using: composite
  steps:
    - name: Setup NodeJS version ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    - name: Cache dependencies
      id: cache
      use: action/cache@v3
      with:
        path: ${{ inputs.working-dir }}/node-modules
        key: node-modules-${{ hashFiles('${{ inputs.working-dir }}/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.output.cache-hit != 'true'
      run: ${{ inputs.target-env == 'dev' && 'npm ci' || 'npm ci --omit=dev' }}
      shell: bash
      working-directory: ${{ inputs.working-dir }}
