name: Cache Name and NPM Dependencies
description: This action allows to cache Node and NPM

inputs:
  node-version:
    description: NodeJS version to use
    default: 20.x
    required: true
  working-dir:
    description: The working directory of the application
    default: .
    required: false

runs:
  using: composite
  steps:
    - name: Setup NodeJS version ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ input.node-version }}
    - name: Cache dependencies
      id: cache
      use: action/cache@v3
      with:
        path: ${{ inputs.working-dir }}/node-modules
        key: node-modules-${{ hashFiles('${{ inputs.working-dir }}/package-lock.json') }}
    - name: Install dependencies
      if: ${{ steps.cache.output.cache-hit != 'true' }}
      run: npm ci
      shell: bash
      working-directory: ${{ inputs.working-dir }}
