name: Using Caching

on:
  workflow_dispatch:
    inputs:
      use-cache:
        description: Whether to execute step cache
        type: boolean
        default: true
      node-version:
        description: Node version
        type: choice
        options:
          - 18.x
          - 20.x
          - 21.x
        default: 20.x
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Testing
        run: echo "testing"
      - name: Building
        run: npm run build
      - name: Deploy
        run: echo "Deploy to nonprod"
      
    # Checkout the code
    # Install dependencies
    # Unit test, building
    # Deploy to nonprod
    
