name: Using Caching

on:
  workflow_dispatch:
    inputs:
      use-cache:
        description: Whether to execute step cache
        type: boolean
        default: true
      node-version:
        description: Node version
        type: choice
        options:
          - 18.x
          - 20.x
          - 21.x
        default: 20.x
jobs:
  install-deps:
    runs-on: ubuntu-latest
    outputs:
      deps-cache-key: ${{ steps.cache-key.outputs.CACHE_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - name: Calculate cache key
        id: cache-key
        run: echo "CACHE_KEY=deps-node-modules-${{ hashFiles('package-lock.json') }}" >> "$GITHUB_OUTPUT"
      - name: Download cached dependencies
        uses: actions/cache@v3
        if: ${{ inputs.use-cache }}
        id: cache
        with:
          path: node_modules
          key: ${{ steps.cache-key.outputs.CACHE_KEY }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo ${{ steps.cache-key.outputs.CACHE_KEY }}
          npm ci
  build:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - name: Testing
        run: echo "testing"
      - name: Building
        run: npm run build
      - name: Deploy
        run: echo "Deploy to nonprod"
      
    # Checkout the code
    # Install dependencies
    # Unit test, building
    # Deploy to nonprod
    
