name: Composite Custom Action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setupe Node and NPM
        uses: .github/actions/composite-cache-deps
        with:
          node-version: 20.x
          working-dir: .
