name: Manage Concurency
run-name: Manage Concurency group-${{ github.workflow }}-${{ github.ref }}

on: workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ping url
        id: ping-url
        uses: ./.github/actions/docker-ping-url
        with:
          url: https://www.invalid-qewqewqeq.com
          max_trials: 5
          delay: 5
