name: Manage Concurency
run-name: Manage Concurency group-${{ github.workflow }}-${{ github.ref }}

on: workflow_dispatch

jobs:
  ping-with-concurrency:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
      - name: Ping url
        id: ping-url
        uses: ./.github/actions/docker-ping-url
        with:
          url: https://www.invalid-qewqewqeq.com
          max_trials: 20
          delay: 5
  ping-without-concurrency:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
      - name: Ping url
        id: ping-url
        uses: ./.github/actions/docker-ping-url
        with:
          url: https://www.invalid-qewqewqeq.com
          max_trials: 20
          delay: 5
