name: Javascript Custom Action
run-name: Javascript Custom Action | env - ${{ inputs.target-env }}

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for dependency updates
        uses: ./.github/actions/js-dependency-update
