name: Composite Custom Action
run-name: Composite Custom Action | env - ${{ inputs.target-env }}

on:
  workflow_dispatch:
    inputs:
      target-env:
        description: Which enviroenment to target
        type: choice
        options:
          - dev
          - prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setupe Node and NPM
        uses: ./.github/actions/composite-cache-deps
        with:
          node-version: 20.x
          working-dir: .
