name: Using artifacts

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-versions: '20.x'
      - name: Download cached dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build code
        run: npm run build
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: dist
          run: ls -R

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: app
          path: dist
      - name: Show folder structure
        run: ls -R
